bnf = {
    "programa": [["declara", "rotina", "corpo"]],
    "corpo": [["inicio", "sentencas", "fim"]],
    "declara": [["dvar", "mais_dc"], ["$"]],
    "mais_dc": [["declara"], ["$"]],
    "dvar": [["declare", "variaveis", "como", "tipo_var"]],
    "tipo_var": [["inteiro"]],
    "variaveis": [["id", "mais_var"]],
    "mais_var": [[",", "variaveis"], ["$"]],
    "rotina": [["proc"], ["func"], ["$"]],
    "proc": [["procedimento", "id", "parametros", "corpo", "rotina"]],
    "func": [["funcao", "id", "parametros", "como", "tipo_funcao", "corpo", "rotina"]],
    "parametros": [["(", "lista_parametros", ")"], ["$"]],
    "lista_parametros": [["lista_id", "como", "tipo_var", "cont_lista_par"]],
    "cont_lista_par": [[";", "lista_parametros"], ["$"]],
    "lista_id": [["id", "cont_lista_id"]],
    "cont_lista_id": [[",", "lista_id"], ["$"]],
    "tipo_funcao": [["inteiro"]],
    "sentencas": [["comando", "mais_sentencas"]],
    "mais_sentencas": [["sentencas"], ["$"]],
    "var_read": [["id", "mais_var_read"]],
    "mais_var_read": [[",", "var_read"], ["$"]],
    "var_write": [["id", "mais_var_write"]],
    "mais_var_write": [[",", "var_write"], ["$"]],
    "comando": [
        ["leia", "(", "var_read", ")"], 
        ["mostre", "(", "var_write", ")"],
        ["para", "id", "de", "expressao", "ate", "expressao", "faca", "sentencas", "fim_faca"],
        ["repita", "sentencas", "ate", "(", "condicao", ")"],
        ["enquanto", "(", "condicao", ")", "faca", "sentencas", "fim_enquanto"],
        ["se", "(", "condicao", ")", "entao", "sentencas", "pfalsa", "fim_se"],
        ["id", "<-", "expressao"],
        ["chamada_procedimento"]
    ],
    "chamada_procedimento": [["id", "argumentos"]],
    "argumentos": [["(", "lista_arg", ")"], ["$"]],
    "lista_arg": [["expressao", "cont_lista_arg"]],
    "cont_lista_arg": [[",", "lista_arg"], "$"],
    "condicao": [["expressao", "relacao", "expressao"]],
    "pfalsa": [["senao", "sentencas"], ["$"]],
    "relacao": [["="], [">"], ["<"], [">="], ["<="], ["<>"]],
    "expressao": [["termo", "outros_termos"]],
    "outros_termos": [
        ["op_ad", "termo", "outros_termos"], 
        ["op_ad", "intnum", "outros_termos"],
        ["id", "outros_termos"],
        ["$"]
    ],
    "op_ad": [["+"], ["-"]],
    "termo": [["fator", "mais_fatores"]],
    "mais_fatores": [["op_mul", "fator", "mais_fatores"], ["$"]],
    "op_mul": [["*"], ["/"]],
    "fator": [["id"], ["intnum"], ["(", "expressao", ")"], ["id", "argumentos"]],
}

rules = [
    ('reserved', 'inicio'),
    ('reserved', 'fim'),
    ('reserved', 'declare'),
    ('reserved', 'como'),
    ('reserved', 'inteiro'),
    ('reserved', 'procedimento'),
    ('reserved', 'funcao'),
    ('reserved', 'como'),
    ('reserved', 'leia'),
    ('reserved', 'mostre'),
    ('reserved', 'para'),
    ('reserved', 'de'),
    ('reserved', 'ate'),
    ('reserved', 'faca'),
    ('reserved', 'fim_faca'),
    ('reserved', 'repita'),
    ('reserved', 'enquanto'),
    ('reserved', 'fim_enquanto'),
    ('reserved', 'se'),
    ('reserved', 'entao'),
    ('reserved', 'fim_se'),
    ('reserved', 'senao'),
    ('delimiter', ','),
    ('delimiter', '\('),
    ('delimiter', '\)'),
    ('delimiter', ';'),
    ('delimiter', '<-'),
    ('operation', '\+'),
    ('operation', '\-'),
    ('operation', '\*'),
    ('operation', '\/'),
    ('relation', '='),
    ('relation', '<'),
    ('relation', '>'),
    ('relation', '<='),
    ('relation', '>='),
    ('relation', '<>'),
    ('intnum', '[0-9]'),
    ('id', '[a-zA-Z]+')
]